using SoundShapesServer.Types.Database;
using SoundShapesServer.Types.Responses.Api.ApiTypes;

namespace SoundShapesServer.Types.Responses.Api.DataTypes;

public record ApiCodeResponse : IApiDbResponse<DbCode, ApiCodeResponse>
{
    public required string Code { get; init; }
    public required ApiMinimalUserResponse User { get; init; }
    public required DateTimeOffset CreationDate { get; init; }
    public required DateTimeOffset ExpiryDate { get; init; }
    public required CodeType CodeType { get; init; }
    
    /// <summary>
    /// The platform that this code was generated by, this is only relevant for registration codes
    /// </summary>
    public required PlatformType? Platform { get; init; }
    /// <summary>
    /// Whether the np ticket that was used to generate this ticket was genuine, this is only relevant for registration codes
    /// </summary>
    public required bool? GenuineNpTicket { get; init; }
    
    public static ApiCodeResponse FromDb(DbCode value)
    {
        return new ApiCodeResponse
        {
            Code = value.Code,
            User = ApiMinimalUserResponse.FromDb(value.User),
            CreationDate = value.CreationDate,
            ExpiryDate = value.ExpiryDate,
            CodeType = value.CodeType,
            Platform = value.Platform,
            GenuineNpTicket = value.GenuineNpTicket,
        };
    }
}