# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore

    # Ensure Docker is running
    - name: Ensure Docker is running
      run: |
        sudo systemctl status docker
        sudo docker info
    
    # Execute tests
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    # Publish for different platforms
    - name: Publish for Linux x64
      run: dotnet publish -c Release -r linux-x64 --self-contained SoundShapesServer

    - name: Publish for Linux ARM64
      run: dotnet publish -c Release -r linux-arm64 --self-contained SoundShapesServer
      
    - name: Publish for Windows x64
      run: dotnet publish -c Release -r win-x64 --self-contained SoundShapesServer
      
    # Upload artifacts for Linux and Windows
    - name: Upload Linux x64 build
      uses: actions/upload-artifact@v3.1.1
      with:
          name: "Sound Shapes Server for Linux x64"
          path: "SoundShapesServer/bin/Release/net8.0/linux-x64/publish/"
          if-no-files-found: error
          retention-days: 30

    - name: Upload Linux ARM64 build
      uses: actions/upload-artifact@v3.1.1
      with:
          name: "Sound Shapes Server for Linux ARM64"
          path: "SoundShapesServer/bin/Release/net8.0/linux-arm64/publish/"
          if-no-files-found: error
          retention-days: 30
          
    - name: Upload Windows x64 build
      uses: actions/upload-artifact@v3.1.1
      with:
          name: "Sound Shapes Server for Windows x64"
          path: "SoundShapesServer/bin/Release/net8.0/win-x64/publish/"
          if-no-files-found: error
          retention-days: 30
